# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:42
from __future__ import unicode_literals

import TeamAppApi.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=100, validators=[TeamAppApi.utils.tele_match]),
        ),
    ]
